name: weather_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

  # Local storage
  shared_preferences: ^2.0.15

  # Svg image
  flutter_svg: ^1.0.3

  # Localization
  intl: ^0.18.1

  # Functional programing thingies
  dartz: ^0.10.0
  rxdart: ^0.27.2
  async: ^2.8.1

  # Service locator
  get_it: ^7.6.0

  # Value equality
  equatable: ^2.0.3

  # Managing configurations
  global_configuration: ^2.0.0

  # network
  connectivity_plus: ^5.0.0
  dio: ^4.0.0

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Flavor
  flutter_flavorizr: ^2.2.1

  # Font
  google_fonts: ^6.1.0

  # Regex validation
  regexed_validator: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^4.1.0
  build_runner:
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
  assets:
    enabled: true
    package_parameter_enabled: false
    style: dot-delimiter

flutter:

  uses-material-design: true

  assets:
    - assets/cfg/
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: true

flavorizr:
  ide: "vscode"

  flavors:
    dev:
      app:
        name: "Weather App - dev"
      android:
        applicationId: "co.me.weather.dev"
        icon: "assets/icons/ic_launcher_dev.png"
      ios:
        bundleId: "co.me.weather.dev"
        icon: "assets/icons/ic_launcher_dev.png"
    stg:
      app:
        name: "Weather App - stg"
      android:
        applicationId: "co.me.weather.stg"
        icon: "assets/icons/ic_launcher_stg.png"
      ios:
        bundleId: "co.me.weather.stg"
        icon: "assets/icons/ic_launcher_stg.png"
    pro:
      app:
        name: "Weather App"
      android:
        applicationId: "co.me.weather"
        icon: "assets/icons/ic_launcher_pro.png"
      ios:
        bundleId: "co.me.weather"
        icon: "assets/icons/ic_launcher_pro.png"